---
title: "National, unified checklist of alien species in Belgium"
author: Peter Desmet, Damiano Oldoni, Lien Reyserhove
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
github-repo: trias-project/unified-checklist
output:
  bookdown::gitbook:
    split_by: rmd
    df_print: paged
    config:
      search: no
      sharing:
        facebook: no
        twitter: yes
        all: []
---

```{r index-setup, include = FALSE}
knitr::opts_chunk$set(
  echo = FALSE, # Exclude code from output by default
  warning = FALSE,
  message = FALSE,
  rownames.print = FALSE # Option for df_print = paged
)
```

# Intro

This document contains and describes all the steps in creating a unified checklist of alien species in Belgium and was developed for the [Tracking Invasive Alien Species (TrIAS) project](http://trias-project.be). By running this document in R, it will create all the necessary data files for the unified checklist.

Load libraries:

```{r echo = TRUE}
library(tidyverse)      # To do data science
library(magrittr)       # To use %<>% pipes
library(here)           # To find files
library(janitor)        # To clean input data
library(digest)         # To generate hashes
library(rgbif)          # To use GBIF services

# devtools::install_github("trias-project/trias")
library(trias)          # To use functions developed for TrIAS
```
